name: Create and Manage Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create .github/copilot-instructions.md
        run: |
          mkdir -p .github
          echo "# GitHub Copilot Instructions\n\n## General Guidelines\n- **Always use the latest and best practices** for the relevant programming language and framework.\n- **Write clean, readable, and maintainable code** with consistent formatting.\n- **Add comments** to explain complex logic and non-obvious decisions.\n- **Use TypeScript for all code suggestions where applicable.\n- **Always use React functional components for frontend development.\n- **Follow the Airbnb JavaScript Style Guide** for JavaScript/TypeScript code.\n- **Follow the PEP 8 Style Guide** for Python code.\n\n## Writing and Editing\n- **Automatically complete code snippets** and functions based on context.\n- **Suggest improvements** to existing code, including refactoring and optimization.\n- **Generate unit tests** for new and modified code.\n- **Ensure all code adheres to the project's coding standards** and best practices.\n\n## Reviewing\n- **Automatically review code changes** for potential bugs, security vulnerabilities, and performance issues.\n- **Provide detailed feedback** on code quality and suggest improvements.\n- **Highlight areas of the code that need further attention** or documentation.\n\n## Auto-Save and Auto-Commit\n- **Auto-save changes** to the file every 5 seconds.\n- **Auto-add changes** to the staging area when a file is saved.\n- **Auto-commit changes** with a descriptive commit message when a file is saved.\n- **Commit messages should follow the conventional commit format** (e.g., , , ).\n\n## Auto-Push\n- **Auto-push changes** to the default branch or the branch you are currently working on when a commit is made.\n- **Ensure all changes are pushed to the remote repository** to keep it up-to-date.\n\n## Additional Instructions\n- **Handle merge conflicts** by suggesting the best resolution based on context.\n- **Automatically create pull requests** for new features or significant changes.\n- **Ensure all changes are reviewed and approved** before merging to the main branch.\n- **Use GitFlow or Trunk-Based Development** as per the project's workflow.\n- **Automatically update dependencies** and run tests before committing.\n- **Generate and update documentation** for new and modified code.\n\n## Example Commit Message\n" > .github/copilot-instructions.md

      - name: Create settings.json
        run: |
          echo "{\n  \"github.copilot.chat.codeGeneration.instructions\": [\n    { \"text\": \"Always use the latest and best practices for the relevant programming language and framework.\" },\n    { \"text\": \"Write clean, readable, and maintainable code with consistent formatting.\" },\n    { \"text\": \"Add comments to explain complex logic and non-obvious decisions.\" },\n    { \"text\": \"Use TypeScript for all code suggestions where applicable.\" },\n    { \"text\": \"Always use React functional components for frontend development.\" },\n    { \"text\": \"Follow the Airbnb JavaScript Style Guide for JavaScript/TypeScript code.\" },\n    { \"text\": \"Follow the PEP 8 Style Guide for Python code.\" }\n  ]\n}" > settings.json

            - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "chore: add GitHub Copilot instructions and update project structure"
            git push origin main
          else
            echo "No changes to commit"
          fi
